### ISSUE TITLE
please change the URI Prefix of your elements from example.com to something else

### ISSUE THREAD

**Issue by MyPyDavid** [MarcoReidelbach/MaRDMO-Questionnaire#7]
Please choose your own specific URI Prefix for your elements and update the xml files. 

At import in RDMO you can choose to to set your own URI Prefix for the elements but I don't think it applies to nested or related items in each element.

Maybe @jwindeck could help you or explain more about this

Usually, it something like https://rdmo.mardi.de/terms 

Reference:
 * https://github.com/MarcoReidelbach/MaRDMO-Export-Plugin/issues/33

**Comment by MarcoReidelbach** [comment]
I will do that asap...

**Comment by MarcoReidelbach** [comment]
Changed base_uri from example.com to rdmo.mardi4nfdi.de
